# Generated by Django 4.1.3 on 2022-11-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talkin', '0002_remove_post_reply_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reply',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
