# Generated by Django 4.1.3 on 2022-11-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talkin', '0003_alter_post_creation_date_alter_reply_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
